// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PipelanerClient is the client API for Pipelaner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PipelanerClient interface {
	Sink(ctx context.Context, opts ...grpc.CallOption) (Pipelaner_SinkClient, error)
}

type pipelanerClient struct {
	cc grpc.ClientConnInterface
}

func NewPipelanerClient(cc grpc.ClientConnInterface) PipelanerClient {
	return &pipelanerClient{cc}
}

func (c *pipelanerClient) Sink(ctx context.Context, opts ...grpc.CallOption) (Pipelaner_SinkClient, error) {
	stream, err := c.cc.NewStream(ctx, &Pipelaner_ServiceDesc.Streams[0], "/pipelaner.service.Pipelaner/Sink", opts...)
	if err != nil {
		return nil, err
	}
	x := &pipelanerSinkClient{stream}
	return x, nil
}

type Pipelaner_SinkClient interface {
	Send(*Message) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type pipelanerSinkClient struct {
	grpc.ClientStream
}

func (x *pipelanerSinkClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *pipelanerSinkClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PipelanerServer is the server API for Pipelaner service.
// All implementations should embed UnimplementedPipelanerServer
// for forward compatibility
type PipelanerServer interface {
	Sink(Pipelaner_SinkServer) error
}

// UnimplementedPipelanerServer should be embedded to have forward compatible implementations.
type UnimplementedPipelanerServer struct {
}

func (UnimplementedPipelanerServer) Sink(Pipelaner_SinkServer) error {
	return status.Errorf(codes.Unimplemented, "method Sink not implemented")
}

// UnsafePipelanerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipelanerServer will
// result in compilation errors.
type UnsafePipelanerServer interface {
	mustEmbedUnimplementedPipelanerServer()
}

func RegisterPipelanerServer(s grpc.ServiceRegistrar, srv PipelanerServer) {
	s.RegisterService(&Pipelaner_ServiceDesc, srv)
}

func _Pipelaner_Sink_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PipelanerServer).Sink(&pipelanerSinkServer{stream})
}

type Pipelaner_SinkServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type pipelanerSinkServer struct {
	grpc.ServerStream
}

func (x *pipelanerSinkServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *pipelanerSinkServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Pipelaner_ServiceDesc is the grpc.ServiceDesc for Pipelaner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pipelaner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pipelaner.service.Pipelaner",
	HandlerType: (*PipelanerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sink",
			Handler:       _Pipelaner_Sink_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
