## grpc_server
#[input.grpc_server]
#buffer = 100
#source_name = "pipelaner"
#port = 9090
#
#[map.filter_grpc_server]
#buffer = 100
#input = "grpc_server"
#source_name = "filter"
#code = '''
#    Data.user.id > 8
#'''
#
#[sink.console_filter_grpc_server]
#buffer = 31
#input = "filter_grpc_server"
#source_name = "console"
#
####### grpc_client
#[input.random_generator]
#buffer = 100
#source_name = "rand"
#
#[map.filter_random_input]
#buffer = 100
#input = "random_generator"
#source_name = "filter"
#code = '''
#    Data.user.id > 5
#'''
#
#[sink.grpc_client]
#buffer = 31
#input = "filter_random_input"
#source_name = "pipelaner"
#port = 9090


### Test multi inputs

[input.test_input]
buffer = 100
threads = 1
source_name = "int"

[map.test_int_transform]
inputs = ["test_input"]
buffer = 100
threads = 1
source_name = "int_tr_e"

[map.test_int_transform_empty]
inputs = ["test_input"]
buffer = 100
threads = 1
source_name = "int_tr_e"

[sink.input1_sink]
buffer = 31
threads = 1
inputs = ["test_int_transform", "test_int_transform_empty"]
source_name = "console"


######## Test Protobuf scaling
#[input.pipelaner]
#buffer = 100
#source_name = "pipelaner"
#host = "localhost"
#port = 50501
#
#
#[sink.pipelaner_sink]
#buffer = 31
#input = "pipelaner"
#source_name = "console"


####### Test1
#[input.input1]
#buffer = 100
#source_name = "cmd"
#exec = ["/usr/bin/log", "stream --style ndjson"]
#
#[sink.input1_sink]
#buffer = 31
#input = "input1"
#source_name = "console"

#
#[map.map1]
#buffer = 21
#input = "input1"
#source_name = "inc"
#threads = 2
#
#[map.map1_map2]
#buffer = 22
#input = "map1"
#source_name = "inc"
#
#[map.map1_map3]
#buffer = 22
#input = "map1"
#source_name = "five"
#
#[sink.map1_map2_sink]
#buffer = 31
#input = "map1_map2"
#source_name = "console"

#[sink.map1_map3_sink]
#buffer = 31
#input = "input1"
#source_name = "console"

######## Test2
#[input.input2]
#buffer = 2
#
#[transform.transform_input2]
#buffer = 22
#input = "input2"
#
#[transform.transform_transform_input2]
#buffer = 22
#input = "transform_input2"
#
#[sink.sink_transform_transform_input2]
#buffer = 32
#input = "transform_transform_input2"

###### Test 3
#[transform.3transform_input1]
#input="input1"
#buffer = 2

#[lane.3transform_input2]
#input="transform_transform_input1"
#buffer = 2

