####### Test1
[input.input1]
buffer = 1
source_name = "int"

[map.transform_input1]
buffer = 21
input = "input1"
source_name = "inc"

[map.transform_transform_input1]
buffer = 22
input = "transform_input1"
source_name = "inc"

[map.five_input2]
buffer = 22
input = "transform_input1"
source_name = "five"

[sink.sink_transform_transform_input1]
buffer = 31
input = "transform_transform_input1"
source_name = "console"

[sink.sink_five_input1]
buffer = 31
input = "five_input2"
source_name = "console"

######## Test2
#[input.input2]
#buffer = 2
#
#[transform.transform_input2]
#buffer = 22
#input = "input2"
#
#[transform.transform_transform_input2]
#buffer = 22
#input = "transform_input2"
#
#[sink.sink_transform_transform_input2]
#buffer = 32
#input = "transform_transform_input2"

###### Test 3
#[transform.3transform_input1]
#input="input1"
#buffer = 2

#[lane.3transform_input2]
#input="transform_transform_input1"
#buffer = 2

