name: Go Lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Install dependencies
        run: |
          go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3.1
          args: --timeout=5m --config=.golangci.yml
          skip-cache: false
          # skip-build-cache: true

          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          # install-mode: "goinstall"
